# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-ts:
    docker:
      # specify the version
      - image: circleci/node:8.12.0

    steps:
      - add_ssh_keys:
          fingerprints:
            - "de:be:02:a0:3e:9f:29:e0:38:1f:44:55:be:a5:3a:49"
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: yarn
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - build-ts
